services:
  - type: web
    name: logo-gen-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: HF_TOKEN
        sync: false
      - key: HF_T2I_MODEL
        value: black-forest-labs/FLUX.1-schnell
      - key: FRONTEND_ORIGINS
        value: http://localhost:5173,https://logo-gen-ten.vercel.app,https://logo-1wkqusnzm-patty1103.vercel.app
